package com.taskqueue.outbox;

import java.time.Instant;

/**
 * Immutable record representing one row in the {@code outbox} table.
 *
 * <p>From distributed-transactions-and-event-sourcing.md: "Write the outbox row
 * inside the same database transaction as the domain change. The relay picks it up
 * asynchronously and publishes it to the broker. This guarantees publish-after-commit
 * without a two-phase commit or distributed transaction."
 *
 * @param id          UUID primary key (generated by Postgres via gen_random_uuid())
 * @param aggregateId the task ID that triggered this event
 * @param eventType   the lifecycle event type (matches TaskEventType.name())
 * @param payload     JSON-serialised TaskEvent
 * @param createdAt   when the row was inserted
 * @param publishedAt when the relay published this row; null = not yet published
 */
public record OutboxRecord(
        String id,
        String aggregateId,
        String eventType,
        String payload,
        Instant createdAt,
        Instant publishedAt) {

    /**
     * Factory for new (unpublished) outbox rows.
     * {@code id} and {@code createdAt} are set by the database defaults, so
     * this constructor leaves them null — the JDBC insert will retrieve them
     * via {@code RETURNING}.
     */
    public static OutboxRecord create(String aggregateId, String eventType, String payload) {
        return new OutboxRecord(null, aggregateId, eventType, payload, null, null);
    }

    /** Returns a copy of this record marked as published at {@code when}. */
    public OutboxRecord published(Instant when) {
        return new OutboxRecord(id, aggregateId, eventType, payload, createdAt, when);
    }

    /** True if the relay has not yet forwarded this record to the broker. */
    public boolean isUnpublished() {
        return publishedAt == null;
    }
}
